server:
  port: 8080
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:mysql://mydb1.c5ye0co6cobn.ap-northeast-2.rds.amazonaws.com:3306/crawl_data
    username: root
    password: Wnsghks189493_
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  type-aliases-package: com.example.demo.entity
